- ansible/README.md
Homebrew cannot always install sshpass, even from a given url. The provided link is to an article which describes an alternative installation method.
Closes: IBM/community-automation/#13
> Add sshpass alternative install instructions link

- ansible/common-service-play/README.md
Expanded the assumptions to make sure oc login was a pre-req for running this play, since now we are referencing users in playbook to use this play on OCP 4.6 AWS manual installations if they want CS.
> Common Service play README updates.

- ansible/request-ocs-play/README.md
- ansible/request-ocs-play/examples/ocs_vars.yml
- ansible/request-ocs-play/examples/ocs_vars_template.yml
- ansible/roles/request-ocs/defaults/main.yml
- ansible/roles/request-ocs/files/ocs_install.sh
- ansible/roles/request-ocs/readme.md
- ansible/roles/request-ocs/tasks/request-ocs.yml
1) Add support for ocs 4.5 when ocp 4.6 is installed.
2) Dynamically figure out what ocp version your using and the select the correct ocs version to install.
> Walt ocs 45ver

- ansible/roles/csi-cephfs-fyre/files/csi-ceph.sh
This PR aims to solve the issue in the link below
https://github.com/IBM/community-automation/issues/68
I have tested the code to work in Jenkins job and the job worked with rook-ceph v1.5.3 being installed without any issue. I have confirmed that the install of rook-ceph v1.4.8 also works with the below code.
> Enable install of rook-ceph v1.5 releases

- ansible/request-ocp-fyre-play/README.md
- ansible/request-ocp-fyre-play/examples/ocp_vars_example.yml
Readme updates for ocp fyre on 4.7 and exposing the site parm in vars file.
> Add site parm and readme update for ocp fyre cluster creates

- ansible/roles/request-ocp-roks/tasks/create-cluster.yml
Following work for the issue opened https://github.com/IBM/community-automation/issues/89, the PR that went it removed a neccessary line of code which provided a value for the `worker_num` required. Just added that line back in
> Ansible Playbook erroring, saying the worker_num cannot be zero

- ansible/request-ocp-ceph-fyre-play/request-ocp-ceph.yml
- ansible/request-ocp-cs-install-fyre-play/request-ocp-cs-install.yml
- ansible/request-ocp-fyre-play/request-ocp-fyre-play.yml
- ansible/roles/request_ocp_fyre/defaults/main.yml
- ansible/roles/request_ocp_fyre/readme.md
fyre_ocp_inf_group is set in defaults/main.yml
The value of ocp-clusters is not valid do to -
I see the playbook had this defined as well.  I am wondering if it should become a param for the playbook too.  So it could be passed in and be used in both places, playbook and role.
> change default host_group for add_host

- ansible/roles/request_ocp_fyre/tasks/request-ocpplus-fyre.yml
- ansible/roles/request_ocp_fyre/tasks/request-quickburn-fyre.yml
The deployed_status can only be  "configuring", "deployed", or "failed".
> change "error" to "failed"

- ansible/csi-cephfs-fyre-play/README.md
- ansible/roles/csi_cephfs_fyre/defaults/main.yml
- ansible/roles/csi_cephfs_fyre/files/csi-ceph.sh
- ansible/roles/csi_cephfs_fyre/tasks/csi_cephfs_fyre.yaml
Fix for issue #139. Added code to patch ServiceAccounts with an ImagePullSecret as documented here https://github.com/rook/rook/blob/master/Documentation/k8s-pre-reqs.md#authenticated-docker-registries. Tested on OCP QuickBurn environments both without specifying registry credentials and with specifying my own DockerHub registry credentials.
> Added ability to authenticate to Docker registry

- ansible/roles/ocp_login/readme.md
updating readme with new kubeconfig_location option.
Default: "$HOME/.kube"
> add new variable kubeconfig_location

- ansible/roles/oc_client_install/tasks/oc-client-install.yml
Swapping ansible.builtin.copy to copy so that older versions of ansible can still like this role.
> oc client install needs to support older ansible

- ansible/roles/ocp_login/tasks/ocp_login.yml
Fyre has renamed the infra nodes to be fully qualified. This updates the automation to work with the new naming
> Updated to support the new Fyre infr node names

- ansible/roles/request_ocp_fyre/defaults/main.yml
- ansible/roles/request_ocp_fyre/tasks/request-ocpplus-fyre.yml
- ansible/roles/request_ocp_fyre/tasks/request-quickburn-fyre.yml
Fyre changed how the infrastructure node within an OCP+ cluster worked. It new name was a fully qualified version of the api machine e.g. api.testinf2.cp.fyre.ibm.com
I have test this on the old style and on the new style.
Note roles like OCP_Login need a seperate fix but that should be covered by #165
> Fix the fyre role to support new style inf node naming

- ansible/roles/provision_ocp_cluster/tasks/provision-cluster.yml
provision_ocp_cluster use RedHat Hive to deploy OCP clusters.  There was no error checking which as causing the playbook to run on without ending on errors.
> add error checking to provision_ocp_cluster

- ansible/roles/request_ocp_roks/tasks/create-cluster.yml
Mostly code provided by Chris Webster. Allows deployment using Travis, which previously failed because there was no output for 20 minutes.
> Update ROKS deploy to use an async call

- ansible/roles/instana_instance_on_prem/tasks/main.yml
Had an issue were instana creds contained: "persistence settings could not be loaded: no settings found: /root/.instana/effective-settings.hcl"
The instanacreds would never regenerate so it couldnt fix itself
> Ensure Secret get regen if they break first time

- ansible/roles/request_ocs_local_storage/tasks/request_ocs_local_storage.yml
Attempted to install OCS on OCP 4.8, it failed.
This workaround worked.
> Fix OCP 4.8 for fyre OCS play

- ansible/roles/csi_cephfs_fyre/files/csi-ceph.sh
this will resolve the problem with having 2 extra drives that come with cluster built using the UI OCP+ or quickburn.
> changing node check and reduce timeout

- ansible/roles/common_services/tasks/install.yml
Common Services moved to ICR.io recently and FYRE systems are being throttled in their downloads, we should increase the timeouts.
> Increase the timeout for ICS install

- ansible/roles/fyrevm_delete/defaults/main.yml
- ansible/roles/fyrevm_delete/tasks/fyrevm_delete.yml
- ansible/roles/fyrevm_provision/defaults/main.yml
- ansible/roles/fyrevm_provision/tasks/fyrevm_provision.yml
The current 999 retries can lead to provision failures taking 33 hours, if the ssh connection fails with a timeout (2 mins) 999 times.
> Reduce retries when things go wrong

- ansible/roles/csi_cephfs_fyre/tasks/csi_cephfs_fyre.yaml
Ansible-core 2.14 fails when `args: warn` is used against a `shell` block. This is blocking the csi-cephfs-fyre play that we need.
> Remove warn args from csi_cephfs

- ansible/roles/fyrevm_provision/tasks/fyrevm_provision.yml
Where we request status from fyre, it should be a get not a POST and we are not sending any body, so we should avoid setting body_format. Setting body_format causes ansible to send json=null.
Fyre is looking to turn on "ModSecurity: Cannot add scalar value without an associated key" which would block such requests. We need to fix our code before fyre breaks us.
> Stop sending json=null to fyre

- ansible/roles/fyrevm_provision/tasks/fyrevm_provision.yml
- ansible/roles/request_ocp_fyre/tasks/request-ocp-fyre.yml
We are causing fyre issues by sending a content-type of "application/json" without any JSON or sending a POST call with no data (when it should probably be a GET).
Where we request status from fyre, it should be a get not a POST and we are not sending any body, so we should avoid setting body_format. Setting body_format causes ansible to send json=null.
Fyre is looking to turn on "ModSecurity: Cannot add scalar value without an associated key" which would block such requests. We need to fix our code before fyre breaks us.
> Fyre json issue

- ansible/roles/csi_cephfs_vmware/tasks/csi_cephfs_vmware.yaml
`warn` has been deprecated in ansible-core 2.14. For this task to work with later versions we need to remove this.
Fix tested using ansible 2.13 (6.7.0) and 2.14 (7.4.0).
This was the error:
`Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends`
> Update csi_cephfs_vmware.yaml to remove use of arg warn

- ansible/galaxy.yml
Ansible galaxy doesnt understand symlink so the roles linked folder within each play cause us to download the same roles many times. Attempt to exclude all plays from galaxy install.
> Avoid downloading plays through ansible galaxy
