IBM/community-automation

ansible/request-crc-fyre-play/Jenkinsfile, ansible/roles/crc_fyrevm/tasks/crc_fyrevm.yml, ansible/roles/crc_install/defaults/main.yml
Adding a Jenkinsfile such that users don't have to clone the framework, or setup ansible etc to run a RedHat CodeReadyContainer instance.
=> Add a supporting Jenkinsfile 

README.md, ansible/request-crc-fyre-play/Jenkinsfile
Update main README.md with request-crc-fyre-play 
Fine tune the set +x in the Jenkinsfile
=> Update main README.md with request-crc-fyre-play 

ansible/common-service-play/examples/cs_vars.yml, ansible/roles/common-services/README.md, ansible/roles/common-services/defaults/main.yml, ansible/roles/common-services/tasks/install.yml, ansible/roles/common-services/tasks/main.yml, ansible/roles/common-services/tasks/uninstall.yml
default: cs_action=install
set:     cs_action=uninstall  for undeployment
install and uninstall tasks included from main task
Changes to be committed:
modified:   examples/cs_vars.yml
modified:   ../roles/common-services/README.md
modified:   ../roles/common-services/defaults/main.yml
new file:   ../roles/common-services/tasks/install.yml
modified:   ../roles/common-services/tasks/main.yml
new file:   ../roles/common-services/tasks/uninstall.yml
=> add parameter cs_action for CS undeployment (#1)

ansible/request-ocp-fyre-play/README.md
=> Fix README for ocp fyre play

ansible/roles/request-ocp-fyre/defaults/main.yml
Update default worker cpu to 8
=> Update worker cpu fyre

ansible/request-ocp-fyre-play/README.md
=> Another README update

ansible/deply-ova-vmware-play/examples/deploy_vmware_vars.yml, ansible/roles/deploy-ova-vmware/tasks/deploy-ova-vmware.yaml
Some fixes for deploy ova intermitant failures.
=> Fix mode of url downloads and examples yaml.

ansible/request-rhel-jmeter-fyre-play/Jenkinsfile, ansible/request-rhel-jmeter-fyre-play/README.md, ansible/request-rhel-jmeter-fyre-play/request-rhel-jmeter-fyre-play.yml, ansible/roles/jmeter/tasks/main.yml, ansible/roles/jmeter_java/tasks/main.yml
Fix'd where the new PATH exports reside
=> jmeter role adjustments 

ansible/request-ocp4-logging-play/examples/inventory_remote_template, ansible/request-ocp4-logging-play/examples/ocp_logging_vars_template.yml
Create example templates for running ocp_logging on remote bastion host.
=> Walt log templates

ansible/request-ocs-play/examples/inventory_remote_template, ansible/request-ocs-play/examples/ocs_vars_template.yml
Add inventory template and ocs_vars template for using in build pooling.
=> OCS templates added for automating

ansible/roles/request-ocs/tasks/request-ocs.yml
Fix ocs tasks to setup correct PATH.
=> Fix ocs task

ansible/roles/request-ocp-fyre/tasks/create-ocpplus-custom-fyre.yml
=> Allowing Rootfs to be supplied if present

ansible/request-ocp-fyre-play/README.md, ansible/roles/request-ocp-fyre/defaults/main.yml, ansible/roles/request-ocp-fyre/tasks/create-ocpplus-quickburn-fyre.yml, ansible/roles/request-ocp-fyre/tasks/request-quickburn-fyre.yml
Add quickburn ocp+ cluster create to request-ocp-fyre-play
=> Walt quickburn

ansible/csi-cephfs-fyre-play/README.md, ansible/roles/csi-cephfs-fyre/defaults/main.yml
Update cephfs version to v1.4.7
=> New cephfs version v1.4.7

ansible/roles/python-install-fyre/tasks/python-install-fyre.yaml
added --nobest so that yum update would not fail on OCP+ INF server
=> adding in --nobest

ansible/request-ocs-fyre-play/README.md, ansible/roles/request-ocs-local-storage/templates/46.local-volume-set.sh.j2
Allow OCS Fyre to install on GUI created OCP+ 4.6 or new clusters.
=> PV count fix

ansible/provision-ocp-cluster-play/examples/common-vars.yml, ansible/provision-ocp-cluster-play/examples/vsphere-vars.yml, ansible/provision-ocp-cluster-play/provision-ocp-cluster-play.yml, ansible/roles/provision-ocp-cluster/tasks/provision-cluster.yml, ansible/roles/provision-ocp-cluster/templates/vsphere-template.j2
Add in the hive vsphere support for provision/delete of a cluster through hive.
=> Walt hive vsphere

ansible/roles/ocp-cluster-tag/tasks/add-tags.yml
added aws cred variables to task.
=> add aws creds

ansible/request-ocp-roks-play/README.md, ansible/request-ocp-roks-play/examples/roks-vars.yml, ansible/roles/request-ocp-roks/defaults/main.yml, ansible/roles/request-ocp-roks/readme.md, ansible/roles/request-ocp-roks/tasks/create-cluster.yml
Added additional documentation, improve defaults, and improve variable handling to help resolve issue #89
=> Updates to variables and instructions on usage

ansible/roles/ocp_pool_claim/tasks/ocp-pool-claim.yml, ansible/roles/provision-ocp-cluster/tasks/provision-cluster.yml
Don't want to leave the terminal logged into the hive hub, so adding a logout call.
=> Add hive HUB logout

README.md, ansible/csi-cephfs-fyre-play/csi-cephfs.yml, ansible/roles/common_services_cat_src_inst/tasks/main.yml, ansible/roles/csi_cephfs_fyre/tasks/main.yml, ansible/roles/recover_expired_certificates/tasks/main.yml, ansible/roles/recover_machine_config/tasks/main.yml, ansible/roles/request_ocp4_logging/tasks/main.yml
Fix issue #103 & removed extra host variable from csi-cephfs play
=> Fix issue #103 & removed extra host variable from csi-cephfs play

ansible/roles/oc_client_install/tasks/main.yml
a reference in main.yml got changed to underscores when it should not have changed.
=> fix underscore reference

ansible/provision-pool-play/Jenkinsfile, ansible/provision-pool-play/Jenkinsfile-aws, ansible/roles/oc_client_install/tasks/oc-client-install.yml, ansible/roles/provision_pool/tasks/provision_pool.yml
=> Walt jenkins

ansible/ocp-pool-claim-play/examples/pool-vars.yml, ansible/ocp-pool-claim-play/ocp-pool-claim-play.yml
multiple logins was affect by passing kubeadmin_password on command line.  This fixes the issue.
=> fix multiple login issue

ansible/roles/ocp_pool_claim/tasks/ocp-pool-claim.yml
changes to logging cluster details
changes to removing previous claim details
changes to removing pools
=> update claim process

ansible/provision-ocp-cluster-play/examples/aws-vars.yml, ansible/provision-ocp-cluster-play/examples/azure-vars.yml, ansible/provision-ocp-cluster-play/examples/common-vars.yml, ansible/provision-ocp-cluster-play/provision-ocp-cluster-play.yml, ansible/roles/provision_ocp_cluster/tasks/provision-cluster.yml, ansible/roles/provision_ocp_cluster/templates/aws-template.j2, ansible/roles/provision_ocp_cluster/templates/azure-osServicePrincipal.json.j2, ansible/roles/provision_ocp_cluster/templates/azure-template.j2
Add azure to provision-ocp-cluster-play
=> Walt azure

ansible/roles/request_ocp_fyre/tasks/request-ocpplus-fyre.yml, ansible/roles/request_ocp_fyre/tasks/request-quickburn-fyre.yml
Grabbing kubeadmin password, access url and other properties for use in future roles like ocp_login
=> Grabbing Extra detail for fyre ocp clusters

ansible/provision-ocp-cluster-play/examples/azure-vars.yml, ansible/provision-ocp-cluster-play/examples/common-vars.yml, ansible/provision-ocp-cluster-play/examples/google-vars.yml, ansible/provision-ocp-cluster-play/provision-ocp-cluster-play.yml, ansible/roles/provision_ocp_cluster/tasks/provision-cluster.yml, ansible/roles/provision_ocp_cluster/templates/google-osServiceAccount.json.j2, ansible/roles/provision_ocp_cluster/templates/google-template.j2
Add hive google cluster create
=> Walt google

ansible/request-ocp-fyre-play/Jenkinsfile, ansible/request-ocp-fyre-play/README.md, ansible/roles/request_ocp_fyre/defaults/main.yml, ansible/roles/request_ocp_fyre/tasks/create-ocpplus-custom-fyre.yml, ansible/roles/request_ocp_fyre/tasks/create-ocpplus-normal-fyre.yml, ansible/roles/request_ocp_fyre/tasks/create-ocpplus-quickburn-fyre.yml, ansible/roles/request_ocp_fyre/tasks/request-ocp-fyre.yml
Not quota to tests, but would like this reviewed.
=> add ssh_key to defaults and update related files

ansible/csi-cephfs-fyre-play/README.md
README update to be more clear about the need additional disks on each worker node.
=> Walt ceph readme

ansible/provision-ocp-cluster-play/readme.md
=> Readme cleanup provisioner

ansible/roles/request_ocp_fyre/defaults/main.yml, ansible/roles/request_ocp_fyre/readme.md, ansible/roles/request_ocp_fyre/tasks/create-ocpplus-custom-fyre.yml, ansible/roles/request_ocp_fyre/tasks/create-ocpplus-normal-fyre.yml, ansible/roles/request_ocp_fyre/tasks/create-ocpplus-quickburn-fyre.yml
tested:
- normal
- custom
- quickburn
-
=> Add group id param

ansible/roles/request_ocs_local_storage/tasks/request_ocs_local_storage.yml
Update ocs local storage to support ocs 4.7
=> Walt ocs47

ansible/roles/csi_cephfs_fyre/files/csi-ceph.sh, ansible/roles/csi_cephfs_fyre/tasks/csi_cephfs_fyre.yaml
=> Fix ability to specify default storage class and Docker registry auth

ansible/common-service-fyre-play/README.md, ansible/common-service-fyre-play/examples/cs_vars_fyre.yml, ansible/common-service-play/README.md, ansible/common-service-play/examples/cs_vars.yml, ansible/roles/common_services/README.md, ansible/roles/common_services/defaults/main.yml, ansible/roles/common_services/tasks/install.yml, ansible/roles/common_services/templates/cs-request.bash.j2
improve `odlm` detection
make default channel as `v3`
=> update var waiting odlm and use v3 channel by default

scripts/common/install-prereqs.sh
added support for ubuntu 20.04
=> Update prereq script

ansible/roles/oc_client_install/defaults/main.yml, ansible/roles/oc_client_install/tasks/oc-client-install.yml
arch was being used to pick the client os type.  I've change the variable from arch to client_os.  It can be linux|mac|windows
=> change variable for client os

ansible/roles/fyrevm_provision/defaults/main.yml, ansible/roles/instana_instance_on_prem/tasks/main.yml
Made instana role idempotent.
Setting facts about version, email and password for use in other roles. 
Minor fix to provision_fyre_vm role.
=> Improvements to instana-on-prem role

ansible/roles/hive_ocp_cluster_provision/tasks/provision-cluster.yml
update the error check to use '>' instead of '=='.  To help end the script when an error occurs.
=> change error checking

ansible/common-service-play/examples/cs_vars.yml, ansible/roles/common_services/README.md
=> use icr.io instead docker.io for common service [skip ci]

scripts/common/install-prereqs.sh, scripts/common/rhel8-functions.sh
updates to make ansible install on RHEL 8
=> fix rhel prereq install

ansible/roles/csi_cephfs_fyre/files/csi-ceph.sh
tested 2 versions of cephfs, both appear to work now.  Anything above and below v1.8.0
=> Cephfs update for newer versions

ansible/roles/jmeter_java/tasks/main.yml, ansible/roles/osprereqs/tasks/Ubuntu.22.yml, ansible/roles/twas_config/scripts/enableCustomProps.py, ansible/roles/twas_config/scripts/jvm.py
1. added ubuntu22 os pre-reqs
2. fixed java jmeter logic error
3. pen test jvm args
=> misc updates

ansible/roles/nfs_client_provisioner_fyre/templates/deployment.yml.j2
=> Update nfs-client-provisioner image to later version

ansible/roles/osprereqs/tasks/RedHat.7.yml, ansible/roles/osprereqs/tasks/RedHat.8.yml, ansible/roles/osprereqs/tasks/RedHat.9.yml, ansible/roles/osprereqs/tasks/SLES.12.yml, ansible/roles/osprereqs/tasks/SLES.15.yml, ansible/roles/osprereqs/tasks/Ubuntu.20.yml, ansible/roles/osprereqs/tasks/Ubuntu.22.yml
Signed-off-by: Steven Schader <schader@us.ibm.com>
=> do not remove the containers* since several hosts now user docker/podman

ansible/roles/fyrevm_provision/defaults/main.yml, ansible/roles/fyrevm_provision/tasks/fyrevm_provision.yml
Also , improve comments on retry values, and make them more sensible
=> Make deploy check retries configurable
